version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
      - 8020:8020
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command:
      [ "start-dev", "--http-port=8020", "--import-realm" ]
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    networks:
      - apps

networks:
  apps:
    driver: bridge